#ifndef AIRWAVES_CONST_PARAMETER_PROJECTOR
#define AIRWAVES_CONST_PARAMETER_PROJECTOR

#include "ofMain.h"

const int cPROJECTOR_WINDOW_WIDTH = 1353;
const int cPROJECTOR_WINDOW_HEIGHT = 1024;

#endif // !AIRWAVES_CONST_PARAMETER_PROJECTOR