#ifndef AIRWAVES_CONST_PARAMETER
#define AIRWAVES_CONST_PARAMETER

#include "ofMain.h"

const int cWINDOW_WIDTH = 1280;
const int cWINDOW_HEIGHT = 720;

typedef enum eCHARACTER_TYPE
{
	eCHARACTER_LION = 0,
	eCHARACTER_MONEY,
	eCHARACTER_ALIEN,
	eCHARACTER_NUM
};


const int cSECOND_TEACHING_TIMEOUT = 5.0;
const int cSECOND_GAMING_TIMEOUT = 10.0;
const int cSECOND_TVC_PLAY = 5.0;


#endif // !AIRWAVES_CONST_PARAMETER
